job_id: solar_flare_forecasting

data:
  train_data_path: /d0/amunozj/git_repos/surya_workshop/data/indices/surya_aws_s3_train.csv
  valid_data_path: /d0/amunozj/git_repos/surya_workshop/data/indices/surya_aws_s3_val.csv
  scalers_path: /d0/amunozj/git_repos/surya_workshop/downstream_apps/template/assets/scalers.yaml
  channels: ['aia94', 'aia131', 'aia171', 'aia193', 'aia211', 'aia304', 'aia335', 'aia1600', 'hmi_m', 'hmi_bx', 'hmi_by', 'hmi_bz', 'hmi_v']
  time_delta_input_minutes: [0]
  time_delta_target_minutes: 60
  ## Downstream-specific label alignment
  flare_index_path: /d0/amunozj/git_repos/surya_workshop/downstream_apps/template/data/hek_flare_catalog.csv
  ds_time_column: start_time    # Column in flare catalog used as the event timestamp
  ds_time_tolerance: 4d         # Maximum allowed offset when matching Surya and flare timestamps
  ds_match_direction: forward   # "forward": predict flares from prior solar state (causal)

model:
  # Backbone
  img_size: 4096
  patch_size: 16
  in_channels: 13
  embed_dim: 1280
  depth: 10
  spectral_blocks: 2
  num_heads: 16
  mlp_ratio: 4.0
  drop_rate: 0.0
  window_size: 2
  dp_rank: 4
  rpe: false
  learned_flow: false
  init_weights: false
  checkpoint_layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  ensemble: null
  nglo: 1
  time_embedding:
    type: linear      # Options: linear, fourier, perceiver
    n_queries: null   # Integer for perceiver; otherwise null
    time_dim: 1       # Number of input timesteps

  # Fine-tuning head
  # Options: global_average | global_max | attention | transformer | class_token
  pooling: class_token
  penultimate_linear_layer: true
  dropout: 0.2
  freeze_backbone: false

  # PEFT LoRA
  use_lora: true
  lora_config:
    r: 8
    lora_alpha: 8
    target_modules: ['q_proj', 'v_proj', 'k_proj', 'out_proj', 'fc1', 'fc2']
    lora_dropout: 0.1
    bias: 'none'

optimizer:
  learning_rate: 0.0001
  max_epochs: 20

pretrained_path: /d0/amunozj/git_repos/surya_workshop/downstream_apps/template/assets/surya.366m.v1.pt
rollout_steps: 0
drop_hmi_probability: 0.0
use_latitude_in_learned_flow: false
dtype: float32
wandb_project: template_flare_regression
